CHANGELOG.md, CoseSign1.Tests/DetachedSignatureFactoryTests.cs, CoseSign1/DetachedSignatureFactory.cs
This adds public methods for creating detached cose signature given a hash of the payload.
=> DetachedSignatureFactory accepts pre-hashed content as payload

.github/workflows/dotnet.yml, CHANGELOG.md
The semver-action defined at https://github.com/wakatime/semver-action/tree/v1.6.0/ was incrementing the last pre-release instead of the most recent build. This commit is an attempt to replace that behavior with the following:
v1.2.3-pre12 becomes v1.2.3-pre13
v1.2.4 becomes v1.2.4-pre1
=> Replace semver action with manual steps

.github/workflows/dotnet.yml, CHANGELOG.md
In the "Increment pre-release tag" build step, we use GitHub commands to get the latest version number. Sometimes GitHub fails to return the last version on the stack.
This PR uses a web request to make sure the new proposed version number is not already in use, and if it is, increments and repeats until it finds a free version number.
=> Make sure new version number not already in use

CHANGELOG.md, CoseDetachedSIgnature.Tests/CoseDetachedSignature.Tests.csproj, CoseHandler.Tests/CoseHandler.Tests.csproj, CoseSign1.Certificates.Tests/CoseSign1.Certificates.Tests.csproj, CoseSign1.Tests/CoseSign1.Tests.csproj, CoseSignTool.tests/CoseSignTool.tests.csproj
To address CVE in moq versions >4.18.4, force 4.18.4.
=> update moq dependency to 4.18.4

CHANGELOG.md, CoseHandler.Tests/CoseSignValidateTests.cs, CoseHandler/CoseHandler.cs, CoseHandler/CoseValidationError.cs, CoseHandler/ValidationFailureCode.cs, CoseHandler/ValidationResult.cs, CoseSignTool.tests/ValidateCommandTests.cs, CoseSignTool/ExitCode.cs, CoseSignTool/GetCommand.cs, CoseSignTool/ValidateCommand.cs
Addresses https://github.com/microsoft/CoseSignTool/issues/66
- The default trust validator used by the validate command line had the AllowUntrusted flag set to true.
- AllowUntrusted cmd option was unused
=> Fixing Command Line False Positives 

CHANGELOG.md, CoseHandler/CoseValidationError.cs, CoseSign1.Abstractions/CoseSign1.Abstractions.csproj, CoseSignTool.tests/MainTests.cs, CoseSignTool/CoseCommand.cs, CoseSignTool/CoseSignTool.cs, CoseSignTool/GetCommand.cs, CoseSignTool/SignCommand.cs, CoseSignTool/ValidateCommand.cs
The CoseSign1 libraries were originally built for .NET Standard 2.1 and later downgraded to 2.0 for compatibility. Microsoft.Bcl.Hash is included in 2.1 but not 2.0, so with the downgrade, certain validation scenarios started to fail because they couldn't find Microsoft.Bcl.Hash. This PR adds the assembly as a dependence of CoseSign1.Abstractions, which fixes the broken scenario. 
It also fixes some usage text that was appearing incorrectly, or in some cases not being displayed at all.
=> Fix missing Microsoft.Bcl.Hash reference

CHANGELOG.md, CoseHandler/CoseValidationError.cs, CoseSignTool/CoseSignTool.cs
Reverting because the primary structure feature is not supported on all frameworks that support .NET Standard 2.0
=> Revert use of primary constructor for CoseValidationError

CHANGELOG.md, CoseHandler/CoseHandler.cs, CoseHandler/ValidationResult.cs, CoseSignTool.tests/MainTests.cs, CoseSignTool.tests/ValidateCommandTests.cs, CoseSignTool/ValidateCommand.cs, docs/CoseSignTool.md
This change prints out information about the X509CertificateChain found within the COSE message upon validation.
=> Adding Validation Option to Output Certificate Chain

CHANGELOG.md, CoseHandler/CoseValidationError.cs, CoseSignTool.tests/MainTests.cs, CoseSignTool/ValidateCommand.cs
- CoseSignTool validate now writes output to stdout instead of stderr
- fixed typo in missing payload error message
=> write validation output to standard out

.github/workflows/dotnet.yml, CHANGELOG.md
This org has transitioned to a read-only GITHUB_TOKEN for GitHub Action workflows. This does break our builds. Fixed using guidance at: https://aka.ms/github-token-perms-changes
tl;dr
Jobs need to explicitly specify the permissions needed to run them.
=> Action Permission Changes

CHANGELOG.md, CoseHandler.Tests/CoseSignValidateTests.cs, CoseHandler/ContentValidationType.cs, CoseHandler/CoseHandler.cs, CoseHandler/CoseHandler.csproj, CoseHandler/CoseValidationError.cs, CoseHandler/ValidationFailureCode.cs, CoseHandler/ValidationResult.cs, CoseSignTool.tests/MainTests.cs, CoseSignTool.tests/ValidateCommandTests.cs, CoseSignTool/ValidateCommand.cs, docs/CoseHandler.md, docs/CoseSignTool.md
The command line verb `validate` does not currently support the validation of "COSE detached signatures" - a COSE signing format that I will refer from this point on as "indirect signing".
Indirect signatures, as it exists presently, constitutes an embedded COSE signature where the embedded content represents the hash of the payload. The hashing algorithm is also encoded in the message.
For indirect signatures, validation requires that the payload be hashed using the same algorithm used in the creation of the COSE message. The computed hash is then compared to the hash stored in the content header to ensure the payload has not been mutated. This pull request updates the CoseSignTool.exe `validate` verb to check if the signature is indirect, in which case the aforementioned extra hash …
=> Command Line Validation of Indirect Signatures

CHANGELOG.md, CoseIndirectSignature/CoseIndirectSignature.csproj, Nuspec/CoseIndirectSignature.nuspec
Following up https://github.com/microsoft/CoseSignTool/pull/78 with corrected Nuspec to reflect change from CoseDetachedSignature to CoseIndirectSignature.
=> Update Nuspec for CoseIndirectSignature

CHANGELOG.md, CoseSignTool/CoseSignTool.csproj
NuGet does not automatically add executables to packages the same way it does for pdbs, dlls, etc. We can get around this by explicitly adding the self-contained exe as a "content" file shipped alongside the bins in the NuGet package.
=> Add .exe to CoseSignTool NuGet

CHANGELOG.md, CoseSignTool.tests/CoseSignTool.tests.csproj, CoseSignTool.tests/MainTests.cs, CoseSignTool.tests/Utils.cs, CoseSignTool.tests/ValidateCommandTests.cs, CoseSignTool/CoseCommand.cs, CoseSignTool/ExitCode.cs, CoseSignTool/SignCommand.cs, CoseSignTool/ValidateCommand.cs
Added error codes to distinguish between missing, empty, and unreadable source files, and integrated them into CoseSignTool.
Added unit tests to cover these cases.
Minor cleanup of other unit tests.
=> more granular error codes

CHANGELOG.md, CoseSign1.Abstractions/CoseSign1.Abstractions.csproj, Nuspec/CoseHandler.nuspec, Nuspec/CoseIndirectSignature.nuspec, Nuspec/CoseSign1.Abstractions.nuspec, Nuspec/CoseSign1.Certificates.nuspec, Nuspec/CoseSign1.nuspec, Nuspec/CoseSignTool.nuspec
NuGet pack errored out on finding LICENSE.md because the LICENSE file doesn't have an extension suffix. Removed the ".md" suffix from LICENSE file references in nuspecs.
=> Fix license filename in nuspecs

CHANGELOG.md, CoseHandler/CoseHandler.csproj, CoseIndirectSignature/CoseIndirectSignature.csproj, CoseSign1.Abstractions/CoseSign1.Abstractions.csproj, CoseSign1.Certificates/CoseSign1.Certificates.csproj, CoseSign1/CoseSign1.csproj, CoseSignTool.sln, CoseSignTool/CoseSignTool.csproj, Nuspec/CoseHandler.nuspec, Nuspec/CoseIndirectSignature.nuspec, Nuspec/CoseSign1.Abstractions.nuspec, Nuspec/CoseSign1.Certificates.nuspec, Nuspec/CoseSign1.nuspec, Nuspec/CoseSignTool.nuspec
Modified the .nuspec and .csproj files to ensure that all of the newly included files appear where they should in the package, and that the pack operation succeeds. Declared the license and readme files so they are visible from the Nuget interface. 
Rearranged the project files for better consistency and readability.
=> Overhaul nuget packaging

CHANGELOG.md, Nuspec/CoseSignTool.nuspec
Removing the "x64" from the file paths in CoseSignTool.nuspec
=> Adjusted file paths in CoseSignTool.nuspec

CHANGELOG.md, CoseHandler.Tests/CoseHandler.Tests.csproj, CoseHandler/CoseHandler.csproj, CoseIndirectSignature.Tests/CoseIndirectSignature.Tests.csproj, CoseIndirectSignature/CoseIndirectSignature.csproj, CoseSign1.Abstractions/CoseSign1.Abstractions.csproj, CoseSign1.Certificates.Tests/CoseSign1.Certificates.Tests.csproj, CoseSign1.Certificates/CoseSign1.Certificates.csproj, CoseSign1.Tests.Common/CoseSign1.Tests.Common.csproj, CoseSign1.Tests/CoseSign1.Tests.csproj, CoseSign1/CoseSign1.csproj, CoseSignTool.Tests/CoseSignTool.Tests.csproj, CoseSignTool/CoseSignTool.csproj
This PR updated all package dependencies except for System.Security.Cryptography.Cose, which includes breaking changes.
=> Update package dependencies

.github/workflows/dotnet.yml, CHANGELOG.md
Attempting to sign using the downloaded CoseSignTool binaries from GitHub returns the following error message:
Could not load file or assembly 'Microsoft.Bcl.HashCode, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
This PR modifies the dotnet publish step in the release workflow to publish self-contained binaries, which do not throw this error.
=> Publish self-contained

CHANGELOG.md, CoseHandler/CoseHandler.cs, CoseSign1.Certificates.Tests/X509ChainTrustValidatorTests.cs, CoseSign1.Certificates/Local/Validators/X509ChainTrustValidator.cs, CoseSign1.Tests.Common/TestCertificateUtils.cs, CoseSignTool.Tests/ValidateCommandTests.cs, CoseSignTool/GetCommand.cs, CoseSignTool/ValidateCommand.cs, docs/CoseSignTool.md
**Feature:** Exposing the "AllowOutdated" option to the command line tool, which enables successful validation of COSE signatures with a certificate chain containing one or more expired nodes. This option has no effect if the signing certificate has the lifetime eku (1.3.6.1.4.1.311.10.3.13).
**BugFix:** The X509ChainTrustValidator now can use all of the certificates included in the x5t header of the COSE message when attempting to build a chain of trust from the signing certificate. Previously, the validator would only use the signing certificate and certificates already installed on machine.
=> Allow outdated and cert chain bug fixes

CHANGELOG.md, CoseHandler/Extensions/FileInfoExtensions.cs, CoseSign1.Tests/StreamExtensionsTests.cs, CoseSign1/CoseSign1MessageFactory.cs, CoseSign1/Extensions/StreamExtensions.cs, CoseSignTool/CoseCommand.cs
When reading large payload files, the check in Stream.IsNullOrEmpty sometimes times out causing an empty payload error before it can complete the read operation. This change increases the timeout for those checks that would result in a Fail result from 100ms to 10 seconds.
=> Increase timeout for checking for empty streams

.github/workflows/dotnet.yml, CHANGELOG.md
Fixes a failure in the publish step on Windows by explicitly setting the shell to bash
=> set shell in publish step

CHANGELOG.md, CoseHandler.Tests/CoseX509ThumbprintTests.cs, CoseIndirectSignature.Tests/IndirectSignatureFactoryTests.cs, CoseIndirectSignature/IndirectSignatureFactory.cs, CoseSign1.Certificates.Tests/X509Certificate2SigningKeyProviderTests.cs, CoseSign1.Certificates/CoseX509Thumbprint.cs
In order to maintain compliance with CodeQL guidelines, all references to weak cryptographic algorithms have been removed from the codebase (`HashAlgorithmName.MD5` and `HashAlgorithmName.SHA1`). 
`HashAlgorithmName.MD5`: All references were from test code, so no behavior was changed for this algorithm (remains unsupported). 
`HashAlgorithmName.SHA1`: Is no longer supported for the creation of new Indirect Signatures, or as a hash algorithm for key providers. To prevent potential security vulnerabilities, consumers should remove any dependencies on this algorithm when using these libraries.
=> Remove Weak Algorithms

.github/workflows/codeql.yml, CoseIndirectSignature.Tests/CoseHashEnvelopeTests.cs, CoseIndirectSignature.Tests/CoseSign1MessageIndirectSignatureExtensionsTests.cs, CoseIndirectSignature.Tests/IndirectSignatureFactoryTests.cs, CoseIndirectSignature.Tests/TestUtils.cs, CoseIndirectSignature/CoseHashEnvelopeHeaderExtender.cs, CoseIndirectSignature/CoseHashV.cs, CoseIndirectSignature/CoseIndirectSignature.csproj, CoseIndirectSignature/Extensions/CoseSign1MessageCoseHashEnvelopeExtensions.cs, CoseIndirectSignature/Extensions/CoseSign1MessageCoseHashVExtensions.cs, CoseIndirectSignature/Extensions/CoseSign1MessageIndirectSignatureExtensions.cs, CoseIndirectSignature/IndirectSignatureFactory.Bytes.cs, CoseIndirectSignature/IndirectSignatureFactory.CoseHashEnvelope.cs, CoseIndirectSignature/IndirectSignatureFactory.CoseHashV.cs, CoseIndirectSignature/IndirectSignatureFactory.Direct.cs, CoseIndirectSignature/IndirectSignatureFactory.Stream.cs, CoseIndirectSignature/IndirectSignatureFactory.cs, CoseSign1.Abstractions/CoseSign1.Abstractions.csproj, CoseSign1.Certificates/CoseSign1.Certificates.csproj, CoseSign1.Tests/CoseSign1.Tests.csproj, CoseSign1/CoseSign1MessageFactory.cs, CoseSignTool.Tests/MainTests.cs, CoseSignTool.Tests/ValidateCommandTests.cs, README.md
Add CoseHashEnvelope support to signing library from https://datatracker.ietf.org/doc/draft-ietf-cose-hash-envelope/03/
This commit introduces a new signature version, `CoseHashEnvelope`, to replace the older `CoseHashV` format. Key changes include:
- Updated `CoseSign1MessageIndirectSignatureExtensionsTests` and `IndirectSignatureFactory` to support the new format.
- Refactored methods for creating indirect signatures to support `CoseHashEnvelope`.
- Added new overload that allow specification for which message format for the factory to create
- Updated existing method signatures to now use `CoseHashEnvelope` as the default format and `CoseHashV` is now the `useOldFormat=true` value.
- Enhanced `CoseSign1Message` with methods to check for `CoseHashEnvelope` presence and retrieve …
=> Add support for CoseHashEnvelope

CHANGELOG.md, CoseIndirectSignature.Tests/CoseHashEnvelopeTests.cs, CoseIndirectSignature/CoseHashEnvelopeHeaderExtender.cs, CoseIndirectSignature/Extensions/CoseSign1MessageCoseHashEnvelopeExtensions.cs
Added support for CoAP pre image content type for validation.  This library will only write content type as tstr for now as that is a much larger contract change.
=> Add support for CoAP preimage content type parsing for validation

CoseSign1.Transparent.CTS/CoseSign1.Transparent.CTS.csproj
Allow beta version of Azure.Security.CodeTransparency in CoseSign1.Transparent.CTS by blocking the NU5104 warning to NuGet Pack can succeed.
=> Allow beta version of Azure.Security.CodeTransparency

CHANGELOG.md, CoseIndirectSignature.Tests/IndirectSignatureFactoryTests.cs, CoseIndirectSignature/IndirectSignatureFactory.Bytes.cs, CoseIndirectSignature/IndirectSignatureFactory.CoseHashEnvelope.cs, CoseIndirectSignature/IndirectSignatureFactory.CoseHashV.cs, CoseIndirectSignature/IndirectSignatureFactory.Direct.cs, CoseIndirectSignature/IndirectSignatureFactory.cs, CoseSign1.Tests/ChainedCoseHeaderExtenderTests.cs, CoseSign1/ChainedCoseHeaderExtender.cs
- Updated IndirectSignatureFactory methods to accept an optional ICoseHeaderExtender parameter for adding custom headers to COSE messages.
- Introduced ChainedCoseHeaderExtender to allow chaining multiple header extenders.
- Added unit tests for ChainedCoseHeaderExtender to ensure correct behavior and error handling.
=> feat: Add header extender support to IndirectSignatureFactory
